<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="MisTest"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="23.005">
  <properties />
            <testcase name="itemExceptionTest" time="23.005" classname="com.mis.market.test.ItemExceptionTest">
                <failure type="java.lang.AssertionError"
                  message="&apos;所有&apos;筛选错误"
              >
<![CDATA[java.lang.AssertionError: '所有'筛选错误
  org.junit.Assert.fail(Assert.java:88)
  org.junit.Assert.assertTrue(Assert.java:41)
  com.mis.market.pages.ItemExceptionPage.filterCheck(ItemExceptionPage.java:31)
  com.mis.market.test.ItemExceptionTest.itemExceptionTest(ItemExceptionTest.java:44)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:497)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:782)
  org.testng.TestRunner.run(TestRunner.java:632)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
  org.testng.SuiteRunner.run(SuiteRunner.java:268)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.run(TestNG.java:1064)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
